import {defineApp,feature} from './domain-config.mjs';
export default defineApp({
  "id": "ai-hospital-implant-charge-capture-recovery",
  "engine": "recovery",
  "title": "Hospital Implant Charge Capture & Vendor Reconciliation",
  "shortTitle": "Implant Revenue Recovery",
  "tagline": "Trace every implant from operating room use through vendor invoice, patient charge, claim, and reimbursement",
  "industry": "Hospital Surgical Revenue Integrity",
  "uiPort": 4576,
  "apiPort": 5576,
  "accent": "#be123c",
  "currency": "USD",
  "primaryOutcome": "Missing or incorrect implant charges identified and converted into compliant corrected claims and recovered net revenue",
  "valueNarrative": "Connect implant masters, UDI data, OR cases, preference cards, vendor invoices, charge masters, claims, and remittances.",
  "calculation": {
    "actualKey": "capturedAmount",
    "expectedKey": "eligibleAmount",
    "actualLabel": "Captured & Reimbursed Amount",
    "expectedLabel": "Supported Eligible Amount",
    "varianceLabel": "Unrecovered supported value",
    "direction": "expected-minus-actual",
    "finding": "Procedure, implant, vendor, coding, and claim evidence indicate uncaptured or under-reimbursed implant value.",
    "actions": [
      "Validate the governing agreement and effective rules",
      "Reconcile transaction-level source evidence",
      "Prepare and submit the recovery or correction package",
      "Track response and reconcile realized financial outcome"
    ]
  }
},[
feature("implant-and-device-master","IRR01","Implant and device master","Reconcile implant and device master using implant masters, UDI and serial data, OR cases, preference cards, implant logs, vendor invoices, charge masters, claim lines, and remittances.","Produce a governed implant and device master decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["procedureImplant","Procedure / Implant","text","OR-2026-8841 / UDI-10842"],["caseReference","Implant and device master Reference","text","IRR01-2026-001"],["capturedAmount","Captured & Reimbursed Amount","currency",486000],["eligibleAmount","Supported Eligible Amount","currency",612500],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"capturedAmount",subjects:["Orthopedic joint case","Cardiac device case","Spine procedure","Trauma implant case","Robotic surgery supply"]}),
feature("vendor-contract-library","IRR02","Vendor contract library","Reconcile vendor contract library using implant masters, UDI and serial data, OR cases, preference cards, implant logs, vendor invoices, charge masters, claim lines, and remittances.","Produce a governed vendor contract library decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["procedureImplant","Procedure / Implant","text","OR-2026-8841 / UDI-10842"],["caseReference","Vendor contract library Reference","text","IRR02-2026-001"],["capturedAmount","Captured & Reimbursed Amount","currency",486000],["eligibleAmount","Supported Eligible Amount","currency",612500],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"capturedAmount",subjects:["Orthopedic joint case","Cardiac device case","Spine procedure","Trauma implant case","Robotic surgery supply"]}),
feature("or-case-ingestion","IRR03","OR case ingestion","Reconcile or case ingestion using implant masters, UDI and serial data, OR cases, preference cards, implant logs, vendor invoices, charge masters, claim lines, and remittances.","Produce a governed or case ingestion decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["procedureImplant","Procedure / Implant","text","OR-2026-8841 / UDI-10842"],["caseReference","OR case ingestion Reference","text","IRR03-2026-001"],["capturedAmount","Captured & Reimbursed Amount","currency",486000],["eligibleAmount","Supported Eligible Amount","currency",612500],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"capturedAmount",subjects:["Orthopedic joint case","Cardiac device case","Spine procedure","Trauma implant case","Robotic surgery supply"]}),
feature("implant-log-ingestion","IRR04","Implant-log ingestion","Reconcile implant-log ingestion using implant masters, UDI and serial data, OR cases, preference cards, implant logs, vendor invoices, charge masters, claim lines, and remittances.","Produce a governed implant-log ingestion decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["procedureImplant","Procedure / Implant","text","OR-2026-8841 / UDI-10842"],["caseReference","Implant-log ingestion Reference","text","IRR04-2026-001"],["capturedAmount","Captured & Reimbursed Amount","currency",486000],["eligibleAmount","Supported Eligible Amount","currency",612500],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"capturedAmount",subjects:["Orthopedic joint case","Cardiac device case","Spine procedure","Trauma implant case","Robotic surgery supply"]}),
feature("barcode-and-udi-reconciliation","IRR05","Barcode and UDI reconciliation","Reconcile barcode and udi reconciliation using implant masters, UDI and serial data, OR cases, preference cards, implant logs, vendor invoices, charge masters, claim lines, and remittances.","Produce a governed barcode and udi reconciliation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["procedureImplant","Procedure / Implant","text","OR-2026-8841 / UDI-10842"],["caseReference","Barcode and UDI reconciliation Reference","text","IRR05-2026-001"],["capturedAmount","Captured & Reimbursed Amount","currency",486000],["eligibleAmount","Supported Eligible Amount","currency",612500],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"capturedAmount",subjects:["Orthopedic joint case","Cardiac device case","Spine procedure","Trauma implant case","Robotic surgery supply"]}),
feature("preference-card-comparison","IRR06","Preference-card comparison","Reconcile preference-card comparison using implant masters, UDI and serial data, OR cases, preference cards, implant logs, vendor invoices, charge masters, claim lines, and remittances.","Produce a governed preference-card comparison decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["procedureImplant","Procedure / Implant","text","OR-2026-8841 / UDI-10842"],["caseReference","Preference-card comparison Reference","text","IRR06-2026-001"],["capturedAmount","Captured & Reimbursed Amount","currency",486000],["eligibleAmount","Supported Eligible Amount","currency",612500],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"capturedAmount",subjects:["Orthopedic joint case","Cardiac device case","Spine procedure","Trauma implant case","Robotic surgery supply"]}),
feature("vendor-invoice-matching","IRR07","Vendor invoice matching","Reconcile vendor invoice matching using implant masters, UDI and serial data, OR cases, preference cards, implant logs, vendor invoices, charge masters, claim lines, and remittances.","Produce a governed vendor invoice matching decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["procedureImplant","Procedure / Implant","text","OR-2026-8841 / UDI-10842"],["caseReference","Vendor invoice matching Reference","text","IRR07-2026-001"],["capturedAmount","Captured & Reimbursed Amount","currency",486000],["eligibleAmount","Supported Eligible Amount","currency",612500],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"capturedAmount",subjects:["Orthopedic joint case","Cardiac device case","Spine procedure","Trauma implant case","Robotic surgery supply"]}),
feature("charge-capture-validation","IRR08","Charge capture validation","Reconcile charge capture validation using implant masters, UDI and serial data, OR cases, preference cards, implant logs, vendor invoices, charge masters, claim lines, and remittances.","Produce a governed charge capture validation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["procedureImplant","Procedure / Implant","text","OR-2026-8841 / UDI-10842"],["caseReference","Charge capture validation Reference","text","IRR08-2026-001"],["capturedAmount","Captured & Reimbursed Amount","currency",486000],["eligibleAmount","Supported Eligible Amount","currency",612500],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"capturedAmount",subjects:["Orthopedic joint case","Cardiac device case","Spine procedure","Trauma implant case","Robotic surgery supply"]}),
feature("hcpcs-and-revenue-code-mapping","IRR09","HCPCS and revenue-code mapping","Reconcile hcpcs and revenue-code mapping using implant masters, UDI and serial data, OR cases, preference cards, implant logs, vendor invoices, charge masters, claim lines, and remittances.","Produce a governed hcpcs and revenue-code mapping decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["procedureImplant","Procedure / Implant","text","OR-2026-8841 / UDI-10842"],["caseReference","HCPCS and revenue-code mapping Reference","text","IRR09-2026-001"],["capturedAmount","Captured & Reimbursed Amount","currency",486000],["eligibleAmount","Supported Eligible Amount","currency",612500],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"capturedAmount",subjects:["Orthopedic joint case","Cardiac device case","Spine procedure","Trauma implant case","Robotic surgery supply"]}),
feature("claim-line-reconciliation","IRR10","Claim-line reconciliation","Reconcile claim-line reconciliation using implant masters, UDI and serial data, OR cases, preference cards, implant logs, vendor invoices, charge masters, claim lines, and remittances.","Produce a governed claim-line reconciliation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["procedureImplant","Procedure / Implant","text","OR-2026-8841 / UDI-10842"],["caseReference","Claim-line reconciliation Reference","text","IRR10-2026-001"],["capturedAmount","Captured & Reimbursed Amount","currency",486000],["eligibleAmount","Supported Eligible Amount","currency",612500],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"capturedAmount",subjects:["Orthopedic joint case","Cardiac device case","Spine procedure","Trauma implant case","Robotic surgery supply"]}),
feature("missing-charge-detection","IRR11","Missing-charge detection","Reconcile missing-charge detection using implant masters, UDI and serial data, OR cases, preference cards, implant logs, vendor invoices, charge masters, claim lines, and remittances.","Produce a governed missing-charge detection decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["procedureImplant","Procedure / Implant","text","OR-2026-8841 / UDI-10842"],["caseReference","Missing-charge detection Reference","text","IRR11-2026-001"],["capturedAmount","Captured & Reimbursed Amount","currency",486000],["eligibleAmount","Supported Eligible Amount","currency",612500],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"capturedAmount",subjects:["Orthopedic joint case","Cardiac device case","Spine procedure","Trauma implant case","Robotic surgery supply"]}),
feature("duplicate-implant-charge-detection","IRR12","Duplicate implant charge detection","Reconcile duplicate implant charge detection using implant masters, UDI and serial data, OR cases, preference cards, implant logs, vendor invoices, charge masters, claim lines, and remittances.","Produce a governed duplicate implant charge detection decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["procedureImplant","Procedure / Implant","text","OR-2026-8841 / UDI-10842"],["caseReference","Duplicate implant charge detection Reference","text","IRR12-2026-001"],["capturedAmount","Captured & Reimbursed Amount","currency",486000],["eligibleAmount","Supported Eligible Amount","currency",612500],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"capturedAmount",subjects:["Orthopedic joint case","Cardiac device case","Spine procedure","Trauma implant case","Robotic surgery supply"]}),
feature("contract-price-variance","IRR13","Contract price variance","Reconcile contract price variance using implant masters, UDI and serial data, OR cases, preference cards, implant logs, vendor invoices, charge masters, claim lines, and remittances.","Produce a governed contract price variance decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["procedureImplant","Procedure / Implant","text","OR-2026-8841 / UDI-10842"],["caseReference","Contract price variance Reference","text","IRR13-2026-001"],["capturedAmount","Captured & Reimbursed Amount","currency",486000],["eligibleAmount","Supported Eligible Amount","currency",612500],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"capturedAmount",subjects:["Orthopedic joint case","Cardiac device case","Spine procedure","Trauma implant case","Robotic surgery supply"]}),
feature("payer-reimbursement-comparison","IRR14","Payer reimbursement comparison","Reconcile payer reimbursement comparison using implant masters, UDI and serial data, OR cases, preference cards, implant logs, vendor invoices, charge masters, claim lines, and remittances.","Produce a governed payer reimbursement comparison decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["procedureImplant","Procedure / Implant","text","OR-2026-8841 / UDI-10842"],["caseReference","Payer reimbursement comparison Reference","text","IRR14-2026-001"],["capturedAmount","Captured & Reimbursed Amount","currency",486000],["eligibleAmount","Supported Eligible Amount","currency",612500],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"capturedAmount",subjects:["Orthopedic joint case","Cardiac device case","Spine procedure","Trauma implant case","Robotic surgery supply"]}),
feature("corrected-claim-workflow","IRR15","Corrected-claim workflow","Reconcile corrected-claim workflow using implant masters, UDI and serial data, OR cases, preference cards, implant logs, vendor invoices, charge masters, claim lines, and remittances.","Produce a governed corrected-claim workflow decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["procedureImplant","Procedure / Implant","text","OR-2026-8841 / UDI-10842"],["caseReference","Corrected-claim workflow Reference","text","IRR15-2026-001"],["capturedAmount","Captured & Reimbursed Amount","currency",486000],["eligibleAmount","Supported Eligible Amount","currency",612500],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"capturedAmount",subjects:["Orthopedic joint case","Cardiac device case","Spine procedure","Trauma implant case","Robotic surgery supply"]}),
feature("procedure-vendor-and-surgeon-analytics","IRR16","Procedure vendor and surgeon analytics","Reconcile procedure vendor and surgeon analytics using implant masters, UDI and serial data, OR cases, preference cards, implant logs, vendor invoices, charge masters, claim lines, and remittances.","Produce a governed procedure vendor and surgeon analytics decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["procedureImplant","Procedure / Implant","text","OR-2026-8841 / UDI-10842"],["caseReference","Procedure vendor and surgeon analytics Reference","text","IRR16-2026-001"],["capturedAmount","Captured & Reimbursed Amount","currency",486000],["eligibleAmount","Supported Eligible Amount","currency",612500],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"capturedAmount",subjects:["Orthopedic joint case","Cardiac device case","Spine procedure","Trauma implant case","Robotic surgery supply"]})
]);
